# Datos del juego — fuente interna para regenerar PDFs
MATERIAS = [{'id': 'historia', 'nombre': 'Historia', 'color_base': 'rojo', 'hex_niveles': ['#FFCCCC', '#FF5555', '#AA0000'], 'bloques': {'1': 3, '2': 3, '3': 2}}, {'id': 'geografia', 'nombre': 'Geografía', 'color_base': 'verde', 'hex_niveles': ['#CCFFCC', '#44BB44', '#006600'], 'bloques': {'1': 3, '2': 3, '3': 2}}, {'id': 'ciencias', 'nombre': 'Ciencias Naturales', 'color_base': 'azul', 'hex_niveles': ['#CCE5FF', '#4499DD', '#004488'], 'bloques': {'1': 3, '2': 3, '3': 2}}, {'id': 'lengua', 'nombre': 'Lengua y Literatura', 'color_base': 'violeta', 'hex_niveles': ['#E8CCFF', '#9955CC', '#551188'], 'bloques': {'1': 3, '2': 3, '3': 2}}, {'id': 'civica', 'nombre': 'Educación Cívica', 'color_base': 'naranja', 'hex_niveles': ['#FFE5CC', '#FF8833', '#BB4400'], 'bloques': {'1': 3, '2': 3, '3': 2}}]

SISTEMA_PUNTOS = {'juego': 'Jenga de Cultura General', 'puntos_por_nivel': {'1': {'nombre': 'Fácil', 'puntos': 1, 'saturacion': 'clara', 'descripcion': 'Bloque con color pálido de la materia'}, '2': {'nombre': 'Medio', 'puntos': 2, 'saturacion': 'media', 'descripcion': 'Bloque con color intermedio de la materia'}, '3': {'nombre': 'Difícil', 'puntos': 3, 'saturacion': 'intensa', 'descripcion': 'Bloque con color más oscuro/intenso de la materia'}}, 'reglas': {'respuesta_incorrecta': 0, 'torre_cae': 'pierde_todos_los_puntos', 'colocar_bloque_si_falla': True}}

MAZOS = {
    "ciencias/1": {'materia_id': 'ciencias', 'materia': 'Ciencias Naturales', 'nivel': 1, 'puntos': 1, 'cartas': [{'id': 1, 'pregunta': '¿Qué gas necesitan las plantas para la fotosíntesis?', 'respuesta': 'Dióxido de carbono (CO₂)'}, {'id': 2, 'pregunta': '¿Cuántos huesos tiene el cuerpo humano adulto?', 'respuesta': '206'}, {'id': 3, 'pregunta': '¿Qué planeta es conocido como el planeta rojo?', 'respuesta': 'Marte'}, {'id': 4, 'pregunta': '¿Cuál es la fórmula química del agua?', 'respuesta': 'H₂O'}]},
    "ciencias/2": {'materia_id': 'ciencias', 'materia': 'Ciencias Naturales', 'nivel': 2, 'puntos': 2, 'cartas': [{'id': 1, 'pregunta': '¿Qué gas respiramos principalmente del aire?', 'respuesta': 'Nitrógeno (~78%)'}, {'id': 2, 'pregunta': '¿Qué órgano produce la bilis en el cuerpo humano?', 'respuesta': 'El hígado'}, {'id': 3, 'pregunta': '¿Qué tipo de energía produce el Sol?', 'respuesta': 'Energía lumínica y térmica (nuclear)'}, {'id': 4, 'pregunta': '¿Qué es un ecosistema?', 'respuesta': 'Sistema formado por seres vivos y su medio ambiente'}]},
    "ciencias/3": {'materia_id': 'ciencias', 'materia': 'Ciencias Naturales', 'nivel': 3, 'puntos': 3, 'cartas': [{'id': 1, 'pregunta': '¿Cuál es el elemento químico con símbolo Au?', 'respuesta': 'Oro'}, {'id': 2, 'pregunta': '¿Qué científico propuso la ley de gravitación universal?', 'respuesta': 'Isaac Newton'}, {'id': 3, 'pregunta': '¿Cuántos cromosomas tiene una célula humana normal?', 'respuesta': '46 (23 pares)'}, {'id': 4, 'pregunta': '¿Qué es la mitosis?', 'respuesta': 'División celular que produce dos células hijas idénticas'}]},
    "civica/1": {'materia_id': 'civica', 'materia': 'Educación Cívica', 'nivel': 1, 'puntos': 1, 'cartas': [{'id': 1, 'pregunta': '¿A qué edad se vota por primera vez en Argentina?', 'respuesta': '18 años (voto obligatorio entre 18 y 70)'}, {'id': 2, 'pregunta': '¿Cuántos poderes del Estado hay en la democracia?', 'respuesta': 'Tres: Ejecutivo, Legislativo y Judicial'}, {'id': 3, 'pregunta': '¿Qué documento es la ley suprema de Argentina?', 'respuesta': 'La Constitución Nacional'}, {'id': 4, 'pregunta': '¿Qué es una democracia?', 'respuesta': 'Sistema donde el pueblo participa en las decisiones políticas'}]},
    "civica/2": {'materia_id': 'civica', 'materia': 'Educación Cívica', 'nivel': 2, 'puntos': 2, 'cartas': [{'id': 1, 'pregunta': '¿Qué es el sufragio universal?', 'respuesta': 'Derecho de votar de todos los ciudadanos adultos'}, {'id': 2, 'pregunta': '¿Qué hace el Poder Judicial?', 'respuesta': 'Administra justicia y aplica las leyes'}, {'id': 3, 'pregunta': '¿Qué son los derechos humanos?', 'respuesta': 'Derechos básicos inherentes a toda persona'}, {'id': 4, 'pregunta': '¿Qué es la laicidad del Estado argentino?', 'respuesta': 'No hay religión oficial; Estado y culto son separados'}]},
    "civica/3": {'materia_id': 'civica', 'materia': 'Educación Cívica', 'nivel': 3, 'puntos': 3, 'cartas': [{'id': 1, 'pregunta': '¿Qué reforma constitucional permitió reelección en Argentina en 1994?', 'respuesta': 'Reforma de 1994 (Constitución en Santa Fe)'}, {'id': 2, 'pregunta': '¿Qué es el federalismo argentino?', 'respuesta': 'División de poder entre Nación y provincias'}, {'id': 3, 'pregunta': '¿Qué organismo controla elecciones en Argentina?', 'respuesta': 'La Cámara Nacional Electoral / justicia electoral'}, {'id': 4, 'pregunta': '¿Qué artículo de la Constitución garantiza la libertad de expresión?', 'respuesta': 'Artículo 14 (entre otros)'}]},
    "geografia/1": {'materia_id': 'geografia', 'materia': 'Geografía', 'nivel': 1, 'puntos': 1, 'cartas': [{'id': 1, 'pregunta': '¿Cuál es la capital de Argentina?', 'respuesta': 'Buenos Aires'}, {'id': 2, 'pregunta': '¿Cuántos países limitan con Argentina?', 'respuesta': '5 (Chile, Bolivia, Paraguay, Brasil, Uruguay)'}, {'id': 3, 'pregunta': '¿Qué océano baña la costa argentina?', 'respuesta': 'El Atlántico'}, {'id': 4, 'pregunta': '¿Cuál es el río más largo de Argentina?', 'respuesta': 'El Paraná'}]},
    "geografia/2": {'materia_id': 'geografia', 'materia': 'Geografía', 'nivel': 2, 'puntos': 2, 'cartas': [{'id': 1, 'pregunta': '¿Cuál es la región más seca de Argentina?', 'respuesta': 'Cuyo / Monte (según escala; también se cita la Puna)'}, {'id': 2, 'pregunta': '¿Qué es el Mercosur?', 'respuesta': 'Bloque comercial regional (Argentina, Brasil, Paraguay, Uruguay y otros)'}, {'id': 3, 'pregunta': '¿Dónde está la Patagonia?', 'respuesta': 'Sur de Argentina y Chile'}, {'id': 4, 'pregunta': '¿Cuál es la capital de la provincia de Córdoba?', 'respuesta': 'Córdoba'}]},
    "geografia/3": {'materia_id': 'geografia', 'materia': 'Geografía', 'nivel': 3, 'puntos': 3, 'cartas': [{'id': 1, 'pregunta': '¿Qué corriente oceánica influye en el clima de la costa argentina?', 'respuesta': 'Corriente de Brasil (cálida) y Corriente Fría de Malvinas'}, {'id': 2, 'pregunta': '¿Cuál es la capital de Australia?', 'respuesta': 'Canberra'}, {'id': 3, 'pregunta': '¿Qué es la línea de Wallace?', 'respuesta': 'Límite biogeográfico entre fauna asiática y australiana'}, {'id': 4, 'pregunta': '¿Qué provincia argentina tiene la mayor superficie?', 'respuesta': 'Buenos Aires'}]},
    "historia/1": {'materia_id': 'historia', 'materia': 'Historia', 'nivel': 1, 'puntos': 1, 'cartas': [{'id': 1, 'pregunta': '¿En qué año se declaró la Independencia de Argentina?', 'respuesta': '1816'}, {'id': 2, 'pregunta': '¿Quién fue el primer presidente argentino?', 'respuesta': 'Bernardino Rivadavia'}, {'id': 3, 'pregunta': '¿Qué civilización construyó Machu Picchu?', 'respuesta': 'Los incas'}, {'id': 4, 'pregunta': '¿En qué continente ocurrió la Segunda Guerra Mundial?', 'respuesta': 'Europa, Asia, África y Oceanía (mundial)'}]},
    "historia/2": {'materia_id': 'historia', 'materia': 'Historia', 'nivel': 2, 'puntos': 2, 'cartas': [{'id': 1, 'pregunta': '¿Qué tratado puso fin a la Primera Guerra Mundial?', 'respuesta': 'Tratado de Versalles (1919)'}, {'id': 2, 'pregunta': '¿Quién lideró la Revolución de Mayo de 1810 en Buenos Aires?', 'respuesta': 'Cornelio Saavedra (y el movimiento criollo)'}, {'id': 3, 'pregunta': '¿En qué año cayó el Muro de Berlín?', 'respuesta': '1989'}, {'id': 4, 'pregunta': '¿Qué país fue aliado de Argentina en la Conquista del Desierto?', 'respuesta': 'No hubo aliado extranjero; fue acción del Estado argentino'}]},
    "historia/3": {'materia_id': 'historia', 'materia': 'Historia', 'nivel': 3, 'puntos': 3, 'cartas': [{'id': 1, 'pregunta': '¿Qué acuerdo entre Rosas y Urquiza terminó con su dominio en 1852?', 'respuesta': 'Pacto de San Nicolás / derrota en Caseros'}, {'id': 2, 'pregunta': '¿En qué batalla San Martín cruzó los Andes hacia Chile?', 'respuesta': 'Campaña de 1817 (batalla de Chacabuco)'}, {'id': 3, 'pregunta': '¿Qué fue la Revolución Rusa de 1917?', 'respuesta': 'Derrocamiento del zarismo e inicio del régimen soviético'}, {'id': 4, 'pregunta': '¿Quién fue el líder del peronismo en su origen?', 'respuesta': 'Juan Domingo Perón'}]},
    "lengua/1": {'materia_id': 'lengua', 'materia': 'Lengua y Literatura', 'nivel': 1, 'puntos': 1, 'cartas': [{'id': 1, 'pregunta': '¿Qué signo de puntuación cierra una pregunta?', 'respuesta': 'El signo de interrogación (¿?)'}, {'id': 2, 'pregunta': '¿Quién escribió El principito?', 'respuesta': 'Antoine de Saint-Exupéry'}, {'id': 3, 'pregunta': '¿Cuál es el plural de «luz»?', 'respuesta': 'Luces'}, {'id': 4, 'pregunta': '¿Qué es un sustantivo?', 'respuesta': 'Palabra que nombra personas, cosas, lugares o ideas'}]},
    "lengua/2": {'materia_id': 'lengua', 'materia': 'Lengua y Literatura', 'nivel': 2, 'puntos': 2, 'cartas': [{'id': 1, 'pregunta': '¿Quién escribió Don Quijote de la Mancha?', 'respuesta': 'Miguel de Cervantes'}, {'id': 2, 'pregunta': '¿Qué es un sinónimo?', 'respuesta': 'Palabra con significado similar a otra'}, {'id': 3, 'pregunta': '¿Qué obra escribió Jorge Luis Borges?', 'respuesta': 'Ficciones, El Aleph, entre otras'}, {'id': 4, 'pregunta': '¿Qué es una metáfora?', 'respuesta': 'Figura literaria que identifica un término con otro'}]},
    "lengua/3": {'materia_id': 'lengua', 'materia': 'Lengua y Literatura', 'nivel': 3, 'puntos': 3, 'cartas': [{'id': 1, 'pregunta': '¿Quién escribió Cien años de soledad?', 'respuesta': 'Gabriel García Márquez'}, {'id': 2, 'pregunta': '¿Qué movimiento literario lideró Rubén Darío?', 'respuesta': 'El modernismo'}, {'id': 3, 'pregunta': '¿Qué es el voseo?', 'respuesta': 'Uso de «vos» como segunda persona (muy común en Argentina)'}, {'id': 4, 'pregunta': '¿Qué poeta argentino escribió Martín Fierro?', 'respuesta': 'José Hernández'}]},
}
